name: Depot Test

on:
  push:
  pull_request:

env:
  BUILD_TYPE: Debug
  # Needed to install Pico SDK
  PICO_SDK_FETCH_FROM_GIT: 1
  DO_NOT_INCREMENT: 1

jobs:
  test_linux_build:
    runs-on: ubuntu-latest
    steps:
      - name: Install Firmware Requisites
        run: sudo apt install -y gcc-arm-none-eabi binutils-arm-none-eabi build-essential
      - name: Get code
        uses: actions/checkout@v3
      - name: Configure CMake for Linux Clients
        run: cmake -B ${{github.workspace}}/linux/build -S ${{github.workspace}}/linux -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build Linux Clients
        run: cmake --build ${{github.workspace}}/linux/build --config ${{env.BUILD_TYPE}}
      - name: Configure CMake for Firmware
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build Firmware
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
      - name: Zap Build
        run: rm -rf ${{github.workspace}}/build
      - name: Configure CMake for Pico Firmware
        env:
          PICO_BOARD: pico
        run: cmake -B ${{github.workspace}}/build -S ${{github.workspace}} -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
      - name: Build Pico Firmware
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
